apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opensearch-fluentbit
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://fluent.github.io/helm-charts'
    targetRevision: 0.20.9
    chart: fluent-bit
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: config.outputs
          value: |-
            [OUTPUT]
                Name opensearch
                Match *
                Host opensearch-cluster-master
                Port 9200
                Index fluent-bit
                Type _doc
                HTTP_User {{ .Values.dashboard_user }}
                HTTP_Passwd admin {{ .Values.dashboard_password }}
                tls On
                tls.verify off
                Suppress_Type_Name On
                Buffer_Size False
                Replace_Dots   On
                Trace_Error    On
                Logstash_Format On
                Logstash_Prefix logstash
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: opensearch
