
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opensearch
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://opensearch-project.github.io/helm-charts'
    targetRevision: 2.6.2
    chart: opensearch
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: persistence.size
          value: {{ .Values.pvc_size }}
        - name: opensearchJavaOpts
          value: '-Xmx512M -Xms512M'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: opensearch
